apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: url-shortener
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: urlshortener
  DATABASE_URL: postgresql+asyncpg://postgres:postgres@db-service:5432/urlshortener
